# Generated by Django 3.1.3 on 2020-11-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=50, verbose_name='gender')),
                ('first_name', models.CharField(max_length=50, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=50, verbose_name='first_name')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='birthdate')),
                ('deathdate', models.DateField(blank=True, null=True, verbose_name='deathdate')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date_updated')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
    ]
