# Generated by Django 3.1.3 on 2020-11-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image_origin',
            field=models.ImageField(blank=True, null=True, upload_to='app/Image/Person/', verbose_name='image'),
        ),
    ]
