# Generated by Django 3.1.3 on 2020-11-18 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_person_image_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childs', models.ManyToManyField(related_name='family_childs', to='app.Person', verbose_name='فرزندان')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_father', to='app.person', verbose_name='پدر')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_mother', to='app.person', verbose_name='مادر')),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Familys',
            },
        ),
    ]
