# Generated by Django 3.1.3 on 2020-11-18 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='childs',
            field=models.ManyToManyField(blank=True, related_name='family_childs', to='app.Person', verbose_name='فرزندان'),
        ),
        migrations.AlterField(
            model_name='family',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_fathers', to='app.person', verbose_name='پدر'),
        ),
        migrations.AlterField(
            model_name='family',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_mothers', to='app.person', verbose_name='مادر'),
        ),
    ]
