# Generated by Django 3.1.3 on 2020-11-24 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_family_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='date_married',
            field=models.DateField(default=datetime.datetime(2020, 11, 24, 20, 14, 19, 295606), verbose_name='date_married'),
            preserve_default=False,
        ),
    ]
