# Generated by Django 3.1.3 on 2020-11-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_family_date_married'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='date_married',
            field=models.DateField(blank=True, null=True, verbose_name='date_married'),
        ),
    ]
